local Vector = require "libs.hump.vector"

TerrainDB = {
	house1 = {
		name			= "house1",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(0, 1),
		["end"]			= Vector(7, 8),
		hitbox_start	= Vector(1, 4),
		hitbox_end		= Vector(6, 7),
	},
	house2 = {
		name			= "house2",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(8, 0),
		["end"]			= Vector(15, 8),
		hitbox_start	= Vector(1, 5),
		hitbox_end		= Vector(6, 8),
	},
	house3 = {
		name			= "house3",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(16, 0),
		["end"]			= Vector(23, 8),
		hitbox_start	= Vector(1, 5),
		hitbox_end		= Vector(6, 8),
	},
	rock1 = {
		name			= "rock1",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(28, 5),
		["end"]			= Vector(30, 8),
		hitbox_start	= Vector(0, 2),
		hitbox_end		= Vector(2, 2),
	},
	rock2 = {
		name			= "rock2",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(28, 9),
		["end"]			= Vector(30, 12),
		hitbox_start	= Vector(0, 2),
		hitbox_end		= Vector(2, 2),
	},
	rock3 = {
		name			= "rock3",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(28, 15),
		["end"]			= Vector(29, 16),
		hitbox_start	= Vector(0, 1),
		hitbox_end		= Vector(1, 1),
	},
	rock4 = {
		name			= "rock4",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(30, 15),
		["end"]			= Vector(31, 16),
		hitbox_start	= Vector(0, 1),
		hitbox_end		= Vector(1, 1),
	},
	tree1 = {
		name			= "tree1",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(28, 0),
		["end"]			= Vector(31, 4),
		hitbox_start	= Vector(1, 3),
		hitbox_end		= Vector(2, 4),
	},
	well1 = {
		name			= "well1",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(24, 0),
		["end"]			= Vector(26, 3),
		hitbox_start	= Vector(0, 2),
		hitbox_end		= Vector(2, 3),
	},
	tent1 = {
		name			= "tent1",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(24, 4),
		["end"]			= Vector(26, 7),
		hitbox_start	= Vector(0, 1),
		hitbox_end		= Vector(2, 3),
	},
	grave1 = {
		name			= "grave1",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(10, 9),
		["end"]			= Vector(11, 10),
		hitbox_start	= Vector(0, 1),
		hitbox_end		= Vector(0, 1),
	},
	grave2 = {
		name			= "grave2",
		image			= "assets/sprites/objects.png",
		offset			= Vector(0, 0),
		start			= Vector(8, 9),
		["end"]			= Vector(9, 10),
		hitbox_start	= Vector(0, 1),
		hitbox_end		= Vector(0, 1),
	},
}
